feat: support stripping out unwanted headers early in the HTTP API request handling stack
When my Netlify function received a POST call with header ("Expect: 100-continue"), it timed out and threw:

BadRequestError: request aborted

This change supports removing unwanted headers entirely early in the processing pipeline.

More background here:
https://linkylinky.netlify.app/vgm5xBjL