Handle contentType not being set
`netlify dev` was failing for me consistently with the following error message:

```
◈ Netlify Dev ◈
◈ No app server detected and no "command" specified
◈ Using current working directory
◈ Unable to determine public folder to serve files from
◈ Setup a netlify.toml file with a [dev] section to specify your dev server settings.
◈ See docs at: https://cli.netlify.com/netlify-dev#project-detection
◈ Running static server from "mybinder.term"

◈ Server listening to 3999

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

TypeError: Cannot read property 'endsWith' of undefined
    at serveRedirect (/usr/local/lib/node_modules/netlify-cli/src/commands/dev/index.js:344:16)
TypeError: Cannot read property 'endsWith' of undefined
    at serveRedirect (/usr/local/lib/node_modules/netlify-cli/src/commands/dev/index.js:344:16)

/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({}) at Error
    at jsStackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

The code was setting `ct` to be an empty object if no content-type header was
set, but then accessing `.type` on the object unconditionally. With this PR,
we set `ct` to be the content-type itself, avoiding any attribute access that
might cause undefined attribute access.